# -*- coding: utf-8 -*-
"""Target_json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1laQ2BhnppSq06VA8rH5h9gG9W2979Z
"""

import json

import pandas as pd

import numpy as np

data = {
    "faturamento": [
        {"dia": "01", "valor": 200},
        {"dia": "02", "valor": 300},
        {"dia": "03", "valor": 0},
        {"dia": "04", "valor": 250},
        {"dia": "05", "valor": 400},
        {"dia": "06", "valor": 0},
        {"dia": "07", "valor": 0},
        {"dia": "08", "valor": 150},
        {"dia": "09", "valor": 500},
        {"dia": "10", "valor": 350}
        # adicione mais dias conforme necessário
    ]
}

with open('faturamento.json', 'w') as f:
    json.dump(data, f)

with open('faturamento.json', 'r') as f:
    json_data = json.load(f)

df = pd.json_normalize(json_data, 'faturamento')

df = df[df['valor'] > 0]

menor = df['valor'].min()
maior = df['valor'].max()

media = df['valor'].mean()

dias_acima_da_media = df[df['valor'] > media].shape[0]

print(f"Menor valor de faturamento: {menor:.2f}")
print(f"Maior valor de faturamento: {maior:.2f}")
print(f"Média do faturamento: {media:.2f}")
print(f"Número de dias com faturamento acima da média: {dias_acima_da_media}")

